using FlightAPI.Data; using FlightAPI.DTOs; using FlightAPI.Models; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace FlightAPI.Controllers;
[ApiController, Route("api/flights")]
public class FlightsController:ControllerBase{private readonly AppDbContext _db; public FlightsController(AppDbContext db){_db=db;}
[HttpGet] public async Task<IActionResult> Get(string? origin,string? destination,DateTime? date,decimal? maxPrice,string? airline){ var q=_db.Flights.Include(f=>f.Airline).Include(f=>f.Route)!.ThenInclude(r=>r!.OriginAirport).Include(f=>f.Route)!.ThenInclude(r=>r!.DestinationAirport).AsQueryable(); if(date.HasValue) q=q.Where(f=>f.DepartureTime.Date==date.Value.Date); if(maxPrice.HasValue) q=q.Where(f=>f.Price<=maxPrice.Value); if(!string.IsNullOrWhiteSpace(airline)) q=q.Where(f=>f.Airline!.Name.Contains(airline)); if(!string.IsNullOrWhiteSpace(origin)) q=q.Where(f=>f.Route!.OriginAirport!.City.Contains(origin)||f.Route.OriginAirport.Code.Contains(origin)); if(!string.IsNullOrWhiteSpace(destination)) q=q.Where(f=>f.Route!.DestinationAirport!.City.Contains(destination)||f.Route.DestinationAirport.Code.Contains(destination)); return Ok(await q.ToListAsync());}
[HttpGet("{id}")] public async Task<IActionResult> One(int id)=>Ok(await _db.Flights.Include(f=>f.Airline).Include(f=>f.Route).FirstOrDefaultAsync(f=>f.Id==id));
[Authorize(Roles="Admin"), HttpPost] public async Task<IActionResult> Create(FlightDto d){var f=new Flight{FlightNumber=d.FlightNumber,AirlineId=d.AirlineId,RouteId=d.RouteId,DepartureTime=d.DepartureTime,ArrivalTime=d.ArrivalTime,Price=d.Price,Status=d.Status}; _db.Flights.Add(f); await _db.SaveChangesAsync(); for(int i=1;i<=30;i++) _db.Seats.Add(new Seat{FlightId=f.Id,SeatNumber=$"A{i}",ClassType=i<=5?"Business":"Economy"}); await _db.SaveChangesAsync(); return Ok(f);} 
[Authorize(Roles="Admin"), HttpPut("{id}")] public async Task<IActionResult> Update(int id,FlightDto d){var f=await _db.Flights.FindAsync(id); if(f==null)return NotFound(); f.FlightNumber=d.FlightNumber; f.AirlineId=d.AirlineId; f.RouteId=d.RouteId; f.DepartureTime=d.DepartureTime; f.ArrivalTime=d.ArrivalTime; f.Price=d.Price; f.Status=d.Status; await _db.SaveChangesAsync(); return Ok(f);} 
[Authorize(Roles="Admin"), HttpDelete("{id}")] public async Task<IActionResult> Delete(int id){var f=await _db.Flights.FindAsync(id); if(f==null)return NotFound(); _db.Flights.Remove(f); await _db.SaveChangesAsync(); return Ok(new{message="Deleted"});}}
