namespace FlightBooking.API.Models;

public class User { public int Id { get; set; } public string FullName { get; set; } = ""; public string Email { get; set; } = ""; public string PasswordHash { get; set; } = ""; public string Role { get; set; } = "User"; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class Airline { public int Id { get; set; } public string Name { get; set; } = ""; public string Code { get; set; } = ""; }
public class Airport { public int Id { get; set; } public string Code { get; set; } = ""; public string Name { get; set; } = ""; public string City { get; set; } = ""; public string Country { get; set; } = ""; }
public class Route { public int Id { get; set; } public int OriginAirportId { get; set; } public Airport OriginAirport { get; set; } = null!; public int DestinationAirportId { get; set; } public Airport DestinationAirport { get; set; } = null!; }
public class Flight { public int Id { get; set; } public string FlightNumber { get; set; } = ""; public int AirlineId { get; set; } public Airline Airline { get; set; } = null!; public int RouteId { get; set; } public Route Route { get; set; } = null!; public DateTime DepartureTime { get; set; } public DateTime ArrivalTime { get; set; } public decimal BasePrice { get; set; } public string Status { get; set; } = "Scheduled"; public List<Seat> Seats { get; set; } = new(); }
public class Seat { public int Id { get; set; } public int FlightId { get; set; } public string SeatNumber { get; set; } = ""; public string SeatClass { get; set; } = "Economy"; public bool IsBooked { get; set; } }
public class Booking { public int Id { get; set; } public string BookingReference { get; set; } = ""; public int UserId { get; set; } public int FlightId { get; set; } public Flight Flight { get; set; } = null!; public int SeatId { get; set; } public Seat Seat { get; set; } = null!; public string PassengerName { get; set; } = ""; public string PassengerEmail { get; set; } = ""; public string Status { get; set; } = "Pending"; public DateTime BookedAt { get; set; } = DateTime.UtcNow; public Payment? Payment { get; set; } }
public class Payment { public int Id { get; set; } public int BookingId { get; set; } public decimal Amount { get; set; } public string Method { get; set; } = "Cash"; public string Status { get; set; } = "Pending"; public DateTime? PaidAt { get; set; } }
