namespace FlightAPI.Models;
public class User { public int Id {get;set;} public string FullName {get;set;}=""; public string Email {get;set;}=""; public string PasswordHash {get;set;}=""; public string Role {get;set;}="User"; public DateTime CreatedAt {get;set;}=DateTime.UtcNow; }
public class Airport { public int Id {get;set;} public string Code {get;set;}=""; public string Name {get;set;}=""; public string City {get;set;}=""; public string Country {get;set;}="Philippines"; }
public class Airline { public int Id {get;set;} public string Name {get;set;}=""; public string Code {get;set;}=""; }
public class Route { public int Id {get;set;} public int OriginAirportId {get;set;} public int DestinationAirportId {get;set;} public Airport? OriginAirport {get;set;} public Airport? DestinationAirport {get;set;} }
public class Flight { public int Id {get;set;} public string FlightNumber {get;set;}=""; public int AirlineId {get;set;} public int RouteId {get;set;} public DateTime DepartureTime {get;set;} public DateTime ArrivalTime {get;set;} public decimal Price {get;set;} public string Status {get;set;}="Scheduled"; public Airline? Airline {get;set;} public Route? Route {get;set;} }
public class Seat { public int Id {get;set;} public int FlightId {get;set;} public string SeatNumber {get;set;}=""; public string ClassType {get;set;}="Economy"; public bool IsBooked {get;set;} }
public class Booking { public int Id {get;set;} public string ReferenceNo {get;set;}=""; public int UserId {get;set;} public int FlightId {get;set;} public int SeatId {get;set;} public string PassengerName {get;set;}=""; public string Status {get;set;}="Confirmed"; public DateTime BookingDate {get;set;}=DateTime.UtcNow; public User? User {get;set;} public Flight? Flight {get;set;} public Seat? Seat {get;set;} }
public class Payment { public int Id {get;set;} public int BookingId {get;set;} public decimal Amount {get;set;} public string Method {get;set;}="Cash"; public string Status {get;set;}="Paid"; public DateTime PaidAt {get;set;}=DateTime.UtcNow; public Booking? Booking {get;set;} }
