using System.Net.Http.Headers; using System.Net.Http.Json;
var api="http://localhost:5000/"; using var client=new HttpClient{BaseAddress=new Uri(api)}; string token="";
while(true){Console.WriteLine("\nFLIGHT BOOKING SYSTEM"); Console.WriteLine("1 Login\n2 Register\n3 Search Flights\n4 Book Flight\n5 My Bookings\n6 Cancel Booking\n0 Exit"); Console.Write("Choose: "); var ch=Console.ReadLine();
if(ch=="0")break;
if(ch=="1"){Console.Write("Email: ");var e=Console.ReadLine();Console.Write("Password: ");var p=Console.ReadLine();var r=await client.PostAsJsonAsync("api/auth/login",new{email=e,password=p});var s=await r.Content.ReadAsStringAsync();Console.WriteLine(s); if(r.IsSuccessStatusCode){token=s.Split("\"token\":\"")[1].Split("\"")[0]; client.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);}}
if(ch=="2"){Console.Write("Full name: ");var n=Console.ReadLine();Console.Write("Email: ");var e=Console.ReadLine();Console.Write("Password: ");var p=Console.ReadLine();var r=await client.PostAsJsonAsync("api/auth/register",new{fullName=n,email=e,password=p});Console.WriteLine(await r.Content.ReadAsStringAsync());}
if(ch=="3"){Console.Write("Origin: ");var o=Console.ReadLine();Console.Write("Destination: ");var d=Console.ReadLine();Console.Write("Date yyyy-mm-dd: ");var dt=Console.ReadLine();Console.WriteLine(await client.GetStringAsync($"api/flights?origin={o}&destination={d}&date={dt}"));}
if(ch=="4"){Console.Write("User ID: ");var uid=int.Parse(Console.ReadLine()!);Console.Write("Flight ID: ");var fid=int.Parse(Console.ReadLine()!);Console.Write("Seat ID: ");var sid=int.Parse(Console.ReadLine()!);Console.Write("Passenger name: ");var pn=Console.ReadLine();var r=await client.PostAsJsonAsync("api/bookings",new{userId=uid,flightId=fid,seatId=sid,passengerName=pn,paymentMethod="Cash"});Console.WriteLine(await r.Content.ReadAsStringAsync());}
if(ch=="5"){Console.Write("User ID: ");var uid=Console.ReadLine();Console.WriteLine(await client.GetStringAsync($"api/bookings?userId={uid}"));}
if(ch=="6"){Console.Write("Booking ID: ");var id=Console.ReadLine();var r=await client.PutAsync($"api/bookings/{id}/cancel",null);Console.WriteLine(await r.Content.ReadAsStringAsync());}}
